
[build]
  command = "npm run build && echo \"(function(window){window.env={API_URL:'$API_URL'}})(this);\" > dist/eFreshli-clone/browser/assets/env.js"
  publish = "dist/eFreshli-clone/browser"
[context.production.environment]
  API_URL = "https://efreshliapi.runasp.net/api"

[[redirects]]
 from = "https://efreshli.netlify.app/*"
  to = "http://efreshli.netlify.app/:splat"
  status = 301
  force = true