
  command = "npm run build && echo \"(function(window){window.env={API_URL:'$API_URL'}})(this);\" > dist/eFreshli-clone/browser/assets/env.js"
  publish = "dist/eFreshli-clone/browser"

[context.production.environment]
  API_URL = "http://efreshliapi.runasp.net/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200