
[build]
  command = "npm run build && echo \"(function(window){window.env={API_URL:'$API_URL'}})(this);\" > dist/eFreshli-clone/browser/assets/env.js"
  publish = "dist/eFreshli-clone/browser"
[context.production.environment]
  API_URL = "http://efreshliapi.runasp.net/api"

[[redirects]]
  from = "/api/*"
  to = "http://efreshliapi.runasp.net/api/:splat"
  status = 200
  force = true
